### ISSUE TITLE
Add SWEET from JPL

### ISSUE THREAD

**Issue by jcoyne** [ruby-rdf/rdf-vocab#28]
http://sweet.jpl.nasa.gov

I'm not sure how to do add this one, because its broken up into several owl files:

http://sweet.jpl.nasa.gov/2.3/reprDataFormat.owl
http://sweet.jpl.nasa.gov/2.3/repr.owl
http://sweet.jpl.nasa.gov/2.3/reprMathSolution.owl
http://sweet.jpl.nasa.gov/2.3/reprMath.owl
http://sweet.jpl.nasa.gov/2.3/relaMath.owl
(and many more)

**Comment by gkellogg** [comment]
Probably want to render them into a single local file, and build from that.

**Comment by bendiken** [comment]
That looks like a substantial ontology. We'll need to begin considering size limitations, or this gem will become a multi-megabyte download.

**Comment by gkellogg** [comment]
Maybe this one should go in it's own gem.

The real issue isn't so much the gem size, but the fact that `Vocabulary.each` faults them all in. Still, some mechanism which would allow vocabularies to be defined, and then loaded when required could improve this, perhaps by using micro-gems for larger vocabularies.

**Comment by bendiken** [comment]
Load time and memory requirements do matter more, but gem size will be a particular concern to, say, Heroku users--as well as anybody who needs to deploy often, re-downloading from RubyGems.org.

Perhaps the solution is indeed to have large vocabularies (DBpedia, SWEET) be their own gems, so that these vocabularies don't adversely affect the 80% (or 99%, even) use cases.
