### ISSUE TITLE
gem version numbering breaks SemVer

### ISSUE THREAD

**Issue by nacengineer** [ruby-rdf/rdf-vocab#44]
You have a hard jump in gemspec requirements for ruby from 2.0 to 2.2 in your latest tiny release version 2.0.3

IMO according to Semantic Versioning 2.0.2 -> 2.0.3 should be non-breaking backwards compatible changes, granted this is normally scoped to your gems libs but in this case the ruby version is a considerable change. Personally I wouldn't expect an tiny change to break my install which this does, capistrano on RHEL. 

I get why you did it as these older versions are EOL or soon to be but perhaps it would be better to relax version in this tiny patch's (2.0.3) ruby requirements to the ruby branch it started on or ideally re-version as 3.0.0 with the the hard requirement on ruby 2.2.0.

**Comment by no-reply** [comment]
Thanks @nacengineer. Sorry about the mess.

@gkellogg can we revoke 2.0.3 and re-release as 2.1.0, following the pattern we used for the core `rdf` gem?

I thought Bundler 1.11 had introduced dependency resolution by `required_ruby_version`, but that hasn't really been working out in practice. I hope this gets better, it's been a nightmare for `rails` and `activesupport` dependencies since 5.0.

**Comment by nacengineer** [comment]
much thanks. was ready for the "upgrade or die" blah blah a lot of rubyists give but figured I'd let you know anyway. 

FWIW a lot of shops don't use the ruby version in bundler for various reasons. I know bad practice but the reality of the ruby world we live in. 

Thanks for the response

**Comment by gkellogg** [comment]
Yeah, it should have been released as 2.1.0. I'll take care of that.
