### ISSUE TITLE
Using https for Schema.org

### ISSUE THREAD

**Issue by typhoon2099** [ruby-rdf/rdf-vocab#58]
`RDF::Vocab::SCHEMA` seems to be failing to pick anything up from sites like eBay due to the fact that they use https in their itemtypes. Can this be overridden/configured to work correctly? Note that the [schema.org](http://schema.org) website now redirects to https by default.

EDIT: The FAQ has a section on http/https (https://schema.org/docs/faq.html#19).

**Comment by gkellogg** [comment]
Schema vocabulary terms using https are invalid, but if it’s something out in the wild, we should provide a solution.

*We could create a reasoner operation to generate “proper” http terms for those encountered, which you would need to run over the dataset prior to query. (Support for entailment regimes would help too)
* We could add terms to the schema vocabulary for each https variant, adding `owl:sameProperty/Class` or something similar. We’d need to com up with a naming scheme, and there would be no automatic equivalence.
* We could create a new parallel vocabulary, like above, but in a different namespace.

The reasoner approach might be the most elegant. Thoughts?

**Comment by typhoon2099** [comment]
Well, perhaps a more elegant solution for me right now would be to do a big old search and replace to convert the https to http before passing into the reader. It's possibly better than my current solution of a parallel query for both schemas.

**Comment by briesenberg07** [comment]
Hi there -- taking a look here because my institution's digital collections software makes use of `RDF::Vocab::SCHEMA.[property]` for the purpose of associating RDF properties with metadata fields. So in our RDF, I see schema prop URIs with `http`. 

But schema.org documentation pages have...

<img width="481" height="246" alt="a screenshot of schema.org online property documentation" src="https://github.com/user-attachments/assets/f7f9d69e-981f-4f99-b107-823359b38775" />  



...and [schema.org for Developers](https://schema.org/docs/developers.html) > Turtle dump has:


```Turtle
@prefix schema: <https://schema.org/> . # https here too
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
...
schema:box a rdf:Property ;
    rdfs:label "box" ;
    rdfs:comment "A box is the area enclosed by the rectangle formed by two points. The first point is the lower corner, the second point is the upper corner. A box is expressed as two points separated by a space character." ;
    schema:domainIncludes schema:GeoShape ;
    schema:rangeIncludes schema:Text .
```
On using http, this discussion includes...

> Schema vocabulary terms using https are invalid

...but vocabulary specs seem to indicate differently per my examples above. 

Was decision to use `http` simply pragmatic, as most data sources are using `http` (seems to be indicated in [the FAQ page linked above](https://schema.org/docs/faq.html#19))? Attempting to determine the best URI form for publishing our data, so seeking clarification. TY!

**Comment by typhoon2099** [comment]
Hello, I'm not sure what the correct answer is, but this discussion was from 6 years ago. `https` is basically the default on the web so I can't see an issue with using it at this point. As you say, the FAQ says that both are valid and you can switch to `https`, so you should probably do that to avoid having to make pages available using both protocols (and miss out on stuff like HSTS).

I'm afraid Gregg passed away recently, and I'm not sure if there's anyone to take up the mantle of maintaining the Ruby implementations for RDF. I don't know if the Gem was updated to handle `https`, but if not then it may have to wait until someone takes ownership of the Github Org: https://lists.w3.org/Archives/Public/public-json-ld-wg/2025Sep/0012.html

**Comment by briesenberg07** [comment]
Just a brief response here -- not the most appropriate place but not sure how else to get in touch @typhoon2099 -- to say thank you for the update and your thoughts, sorry to hear this sad news.

**Comment by doriantaylor** [comment]
Just adding that `RDF::Vocab::SCHEMAS` has the `https:` scheme.
