### ISSUE TITLE
still not clear on how to gen vocab

### ISSUE THREAD

**Issue by dsisnero** [ruby-rdf/rdf-vocab#75]
Do I need to clone the rdf vocabulary or can I generate a new vocab by installing this ?

gem install rdf-vocab

`rdf gen-vocab http://www.w3id.org/bot/bot.ttl`
Generate Vocabulary
rdf: Must specify vocabulary UIR

`rdf gen-vocab --uri http://www.w3id.org/bot/bot.ttl`
Generate Vocabulary
F:/windows/tools/ruby/Ruby31-x64/lib/ruby/gems/3.1.0/gems/rdf-vocab-3.2.1/lib/rdf/vocab.rb:400:in `const_missing': uninitialized constant RDF::Vocab::BOT (NameError)
Did you mean?  RDF::Vocab::WOTcd

update README to show that you need to clone this repository to generate vocab documents

**Comment by gkellogg** [comment]
You’ll need to creat an appropriate entry in lib/rdf/vocab.rb, which should be enough. But, every new vocabulary added creates a burden for those including the gem, so there should be some evidence of wide-spread use of the vocabulary. Otherwise, you can use essentially the same workflow to add it to any particular application.
